# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{auto_tagger}
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Jeff Dean}, %q{Brian Takita}, %q{Mike Grafton}, %q{Bruce Krysiak}, %q{Pat Nakajima}, %q{Jay Zeschin}, %q{Mike Barinek}, %q{Sarah Mei}, %q{Mike Dalessio}, %q{Dave Yeu}]
  s.date = %q{2010-09-10}
  s.email = %q{jeff@zilkey.com}
  s.executables = [%q{autotag}]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "auto_tagger.gemspec",
    "bin/autotag",
    "features/autotag.feature",
    "features/deployment.feature",
    "features/step_definitions/autotag_steps.rb",
    "features/step_definitions/deployment_steps.rb",
    "features/step_definitions/shared_steps.rb",
    "features/support/env.rb",
    "features/support/step_helpers.rb",
    "features/templates/cap_ext_deploy.erb",
    "features/templates/deploy.erb",
    "features/templates/stage.erb",
    "lib/auto_tagger.rb",
    "lib/auto_tagger/base.rb",
    "lib/auto_tagger/capistrano_helper.rb",
    "lib/auto_tagger/command_line.rb",
    "lib/auto_tagger/commander.rb",
    "lib/auto_tagger/configuration.rb",
    "lib/auto_tagger/deprecator.rb",
    "lib/auto_tagger/git/ref.rb",
    "lib/auto_tagger/git/ref_set.rb",
    "lib/auto_tagger/git/repo.rb",
    "lib/auto_tagger/options.rb",
    "lib/auto_tagger/recipes.rb",
    "spec/auto_tagger/base_spec.rb",
    "spec/auto_tagger/capistrano_helper_spec.rb",
    "spec/auto_tagger/command_line_spec.rb",
    "spec/auto_tagger/commander_spec.rb",
    "spec/auto_tagger/configuration_spec.rb",
    "spec/auto_tagger/git/ref_set_spec.rb",
    "spec/auto_tagger/git/ref_spec.rb",
    "spec/auto_tagger/git/repo_spec.rb",
    "spec/auto_tagger/options_spec.rb",
    "spec/auto_tagger/recipes_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/zilkey/auto_tagger}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{Helps you automatically create tags for each stage in a multi-stage deploment and deploy from the latest tag from the previous environment}
  s.test_files = [
    "spec/auto_tagger/base_spec.rb",
    "spec/auto_tagger/capistrano_helper_spec.rb",
    "spec/auto_tagger/command_line_spec.rb",
    "spec/auto_tagger/commander_spec.rb",
    "spec/auto_tagger/configuration_spec.rb",
    "spec/auto_tagger/git/ref_set_spec.rb",
    "spec/auto_tagger/git/ref_spec.rb",
    "spec/auto_tagger/git/repo_spec.rb",
    "spec/auto_tagger/options_spec.rb",
    "spec/auto_tagger/recipes_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, ["= 0.8.7"])
      s.add_runtime_dependency(%q<rspec>, ["= 2.0.0.beta.19"])
      s.add_runtime_dependency(%q<cucumber>, ["= 0.8.5"])
      s.add_runtime_dependency(%q<capistrano>, ["= 2.5.18"])
      s.add_runtime_dependency(%q<capistrano-ext>, ["= 1.2.1"])
      s.add_runtime_dependency(%q<jeweler>, ["= 1.4.0"])
      s.add_runtime_dependency(%q<capistrano>, [">= 2.5.3"])
    else
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<rspec>, ["= 2.0.0.beta.19"])
      s.add_dependency(%q<cucumber>, ["= 0.8.5"])
      s.add_dependency(%q<capistrano>, ["= 2.5.18"])
      s.add_dependency(%q<capistrano-ext>, ["= 1.2.1"])
      s.add_dependency(%q<jeweler>, ["= 1.4.0"])
      s.add_dependency(%q<capistrano>, [">= 2.5.3"])
    end
  else
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<rspec>, ["= 2.0.0.beta.19"])
    s.add_dependency(%q<cucumber>, ["= 0.8.5"])
    s.add_dependency(%q<capistrano>, ["= 2.5.18"])
    s.add_dependency(%q<capistrano-ext>, ["= 1.2.1"])
    s.add_dependency(%q<jeweler>, ["= 1.4.0"])
    s.add_dependency(%q<capistrano>, [">= 2.5.3"])
  end
end

